import StyledComponentsRegistry from './lib/registry'
import { Roboto } from '@next/font/google'
import '@/app/global.css'

const roboto = Roboto({
	weight: ['400', '700'],
	style: ['italic', 'normal'],
	subsets: ['latin'],
	variable: '--font-roboto',
	display: 'optional',
})

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html className={roboto.variable}>
			<body>
				<StyledComponentsRegistry>{children}</StyledComponentsRegistry>
			</body>
		</html>
	)
}
